### ISSUE TITLE
ES 5.0?

### ISSUE THREAD

**Issue by crashish** [jlinn/elasticsearch-analysis-url#14]
Any plans on supporting Elasticsearch 5?

**Comment by jlinn** [comment]
Definitely.  I updated the code to work with ES 5 last weekend, but I ran into some trouble with Java security permissions when running the tests.  I'm hoping to resolve those issues this weekend.

**Comment by jlinn** [comment]
[v5.0.0.0](https://github.com/jlinn/elasticsearch-analysis-url/releases/tag/v5.0.0.0) has been released.  Let me know if you encounter any issues.

**Comment by yjkhngds** [comment]
prefect!

**Comment by netcelli-tux** [comment]
I'm running Es 5.0.1 but indexing fails:

> java.util.ConcurrentModificationException
	at java.util.ArrayList.sort(ArrayList.java:1456) ~[?:1.8.0_31]
	at org.elasticsearch.index.analysis.url.URLTokenizer.setParts(URLTokenizer.java:94) ~[?:?]
	at org.elasticsearch.index.analysis.url.URLTokenFilter.tokenize(URLTokenFilter.java:179) ~[?:?]
	at org.elasticsearch.index.analysis.url.URLTokenFilter.advance(URLTokenFilter.java:147) ~[?:?]
	at org.elasticsearch.index.analysis.url.URLTokenFilter.incrementToken(URLTokenFilter.java:122) ~[?:?]

I can reproduce it every time with bulk indexing.

**Comment by jlinn** [comment]
Interesting.  Would you mind posting the mapping you're using so that I can reproduce it in a test?
