### ISSUE TITLE
Seems to fail on urls without paths

### ISSUE THREAD

**Issue by skyshard** [jlinn/elasticsearch-analysis-url#7]
Trying to index something like `https://www.google.com` throws this error:

```
java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(ArrayList.java:854)
	at org.elasticsearch.index.analysis.url.URLTokenFilter.incrementToken(URLTokenFilter.java:101)
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:634)
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:365)
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:321)
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocuments(DocumentsWriterPerThread.java:273)
	at org.apache.lucene.index.DocumentsWriter.updateDocuments(DocumentsWriter.java:413)
	at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1318)
	at org.apache.lucene.index.IndexWriter.addDocuments(IndexWriter.java:1297)
	at org.elasticsearch.index.engine.InternalEngine.innerIndex(InternalEngine.java:528)
	at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:457)
	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:601)
	at org.elasticsearch.index.engine.Engine$Index.execute(Engine.java:836)
	at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:237)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:326)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:119)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:68)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:639)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:271)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

with these analyzer settings

```
"analysis": {
        "filter": {
          "url_path": {
            "tokenize_path": "false",
            "type": "url",
            "allow_malformed": "true",
            "tokenize_query": "false",
            "part": "path"
          }
        },
        "analyzer": {
          "url_host": {
            "tokenizer": "url_host"
          },
          "url_path": {
            "filter": [
              "url_path"
            ],
            "tokenizer": "whitespace"
          }
        },
        "tokenizer": {
          "url_host": {
            "tokenize_path": "false",
            "type": "url",
            "allow_malformed": "true",
            "tokenize_query": "false",
            "part": "host"
          }
        }
      }
```

The error seems to have started somewhere between the 1.7.x compatible version and the 2.x compatible version

**Comment by skyshard** [comment]
Failing test in #8

**Comment by jlinn** [comment]
Thanks for pointing this out.  It should be fixed now.
